### PR TITLE
feat: 🎸 apply base singular capabilities to account

### PR DESCRIPTION
**Pull request by randallmorey**
This PR applies base capabilities to singular accounts (`read`, `update`, `delete`, and `save`).

### CODE REVIEW

**Review by randallmorey — COMMENTED** [review]
Note that acceptance tests have be reorganised to include separate test files for `accounts/delete`, `accounts/update`, and `accounts/read`, all of which now have new test cases for capabilities.  This cleans up the main acceptance test file which was growing too large.

**Comment by gsusmi** [comment]
Looks great! Especially like breaking up tests into actions.
Query: Where are the ember-can abilities defined? Is that not necessary??

**Comment by gsusmi** [comment]
@randallmorey , I can't see `can 'update model'` being used in this example - is `can 'save model'` the preferred method?

**Comment by randallmorey** [comment]
> @randallmorey , I can't see `can 'update model'` being used in this example - is `can 'save model'` the preferred method?

Yes.  The `save` permission is a composite that includes an `update` check.  There's a comment in the `canSave` getter of the ability explaining why it is necessary.

**Review by DhariniJeeva — APPROVED** [review]

**Pull request merged**
