### PR TITLE
fix missing account ids

### PR DESCRIPTION
**Pull request by DhariniJeeva**
During the recent HDS migration, the account IDs were incorrectly added.

before
Screenshot 2023-07-27 at 1 33 32 PM

after:
 
Screenshot 2023-07-27 at 1 37 11 PM

### CODE REVIEW

**Review by calcaide — APPROVED** [review]
Nice one!! thanks for catching this!! :dancer:

**Comment by calcaide** [comment]
@DhariniJeeva 
**None blocking comment:** I notice this PR brings changes within `yarn.lock` but your changes does not seem to provoke that. Perhaps your branch is out of sync or we have an outdated `yarn.lock` in main, just mentioning in case you want to check that 😉

**Comment by DhariniJeeva** [comment]
> @DhariniJeeva **None blocking comment:** I notice this PR brings changes within `yarn.lock` but your changes does not seem to provoke that. Perhaps your branch is out of sync or we have an outdated `yarn.lock` in main, just mentioning in case you want to check that 😉

yeah, I noticed that locally, I believe the main is out of sync?

**Comment by calcaide** [comment]
@DhariniJeeva Gotcha!! then thsi PR will fix it!! thanks for it! 🥳

**Pull request merged**
