### PR TITLE
Storybook badge updates

### PR DESCRIPTION
**Pull request by DhariniJeeva**
[Jira](https://hashicorp.atlassian.net/browse/ICU-6551)

This pr updates the badge storybook to add a deprecation warning and displays usage of the HDS badge component.

[Badge Storybook](https://boundary-ui-storybook-git-storybook-badge-updates-hashicorp.vercel.app/?path=/docs/rose-badge--hds-badge)

### CODE REVIEW

**Review by ZedLi — APPROVED** [review]
Left a few minor comments

**Review by randallmorey — CHANGES_REQUESTED** [review]
I'd move the HDS usage to the top of the story, after the blurb explaining that rose/badge is deprecated.

**Comment by DhariniJeeva** [comment]
> I'd move the HDS usage to the top of the story, after the blurb explaining that rose/badge is deprecated.

[I moved it up](https://boundary-ui-storybook-d0a1co8ke-hashicorp.vercel.app/?path=/docs/rose-badge--rose-badge-style-legend) and added a note to mention that the HDS replaces the deprecated Rose component for more clarity.

**Review by lisbet-alvarez — APPROVED** [review]
LGTM

**Review by calcaide — APPROVED** [review]
LGTM!!

**Review by randallmorey — APPROVED** [review]

**Pull request merged**
