### PR TITLE
chore: 🤖 add resolution for micromatch

### PR DESCRIPTION
**Pull request by lisbet-alvarez**
# Description

Adding resolution for micromatch removes the need for resolution on braces since braces is a dep. of micromatch. 
Below are the dependencies that use micromatch:
- micromatch@^3.1.4 -> anymatch@^2.0.0 -> sane@^4.0.0 -> broccoli@^3.5.2 -> **ember-cli@^4.12.2**
- micromatch@^3.1.4 -> sane@^4.0.0 -> broccoli@^3.5.2 -> **ember-cli@^4.12.2**
- micromatch@^3.1.4 -> find-yarn-workspace-root@^1.2.1 -> **ember-cli-dependency-checker@^3.3.2**
We should def. update ember-cli to v5 (i added as a techtime topic). Resolution will still be needed because we are already using newest version of **ember-cli-dependency-checker**.

Resolve dependabot alerts [#156](https://github.com/hashicorp/boundary-ui/security/dependabot/156l) && [#106](https://github.com/hashicorp/boundary-ui-enterprise/security/dependabot/106)

## How to Test

1. `yarn start` in `ui/admin`
2. `yarn start:desktop` in `ui/desktop`
3. [boundary-ui-releases test run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10779548444)

## Checklist

- [ ] I have added before and after screenshots for UI changes
- [ ] I have added JSON response output for API changes
- [ ] I have added steps to reproduce and test for bug fixes in the description
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by cameronperera — APPROVED** [review]
LGTM

**Review by ZedLi — APPROVED** [review]
image

Love to see it

**Review by DhariniJeeva — APPROVED** [review]
looks good!

**Review by calcaide — APPROVED** [review]
Amazing clean up!!! 🙌

**Pull request merged**
