### PR TITLE
chore: 🤖 Update ember-try

### PR DESCRIPTION
**Pull request by calcaide**
Update `ember-try` from `1.4.0` to `2.0.0`. As [per changelog](https://github.com/ember-cli/ember-try/blob/master/CHANGELOG.md) there is no risk on the update

### CODE REVIEW

**Review by cameronperera — APPROVED** [review]
What caused all the deletions from the yarn.lock file?

**Review by randallmorey — CHANGES_REQUESTED** [review]
Are we even using Ember Try?  If not, we can probably rip out the dep altogether.

**Comment by calcaide** [comment]
> Are we even using Ember Try? If not, we can probably rip out the dep altogether.

@randallmorey That's actually a good point.

I assumed we use to run tests with different ember versions as is specified in the API project, [here](https://github.com/hashicorp/boundary-ui/tree/main/addons/api#yarn-commands) at the `test:all` row it says:
`Runs tests across multiple Ember versions with ember-try.`

I checked `ember-try` documentation on how to use it ([link here](https://github.com/ember-cli/ember-try)) but the thing is I do not find the implementation in our code base. So I think you are right, we aren't using it :)

I will triple check that, close this PR and provide a new one to get rid of `ember-try`.

Thank you for the feedback and nice catch!!

**Comment by calcaide** [comment]
@randallmorey 

Closing this PR in favour of deprecating `ember-try` in [this new PR](https://github.com/hashicorp/boundary-ui/pull/1002)

**Pull request closed without merging**
