### PR TITLE
test(e2e): Fix flakiness when selecting org links

### PR DESCRIPTION
**Pull request by moduli**
This PR addresses some flaky failures on some Admin UI tests. 

Some links exist on both the `Global` and `Org` scope, like `Storage Policies` and `Auth Methods`. This can potentially cause some issues where the test navigates to the desired Org and selects the Org variant of a link, but the test moves too quickly and selects the `Global` variant before the `Org` page is able to load. 

We saw this issue on a session recording test when the test would try to navigate to a policy it created in an org, but the policy wasn't showing up on the page. We noticed that the scope of the page was still in `Global`.

This PR modifies some tests to ensure that the Org page has loaded after navigating to the desired org before proceeding. 

## Testing
The tests that are affected by this include...
- Auth Method (password)
- Session Recording (AWS)
- Session Recording (MinIO)

To be able to run all of the tests, you'll need to use the boundary-enterprise and run tests against 2 different scenarios.
```
enos scenario launch e2e_ui_docker_ent builder:local
yarn run e2e:ent:docker

enos scenario launch e2e_ui_aws_ent builder:local
yarn run e2e:ent:aws
```

### CODE REVIEW

**Review by calcaide — COMMENTED** [review]
When running `yarn run e2e:ent:docker` under `enos scenario launch e2e_ui_docker_ent builder:local` env I am getting a worker-ent test failure (attached screenshot).

I did some debug and I do believe the test is failing because the `data-test-*` selector used does not exists in any template. 
The selector used is `[data-test-worker-directory]` but not present on `.hbs` files, therefore, is not finding the element in the DOM

I do think such test failure is NOT related to this changes. The session-recording tests pass no problem.

Screenshot 2024-06-19 at 2 56 35 PM

**Review by calcaide — CHANGES_REQUESTED** [review]
When running `yarn run e2e:ent:aws` under `enos scenario launch e2e_ui_aws_ent builder:local` env I am getting [the previously reported work-ent test failure](https://github.com/hashicorp/boundary-ui/pull/2348#pullrequestreview-2129083647).

Also a new error has shown (attached screenshot) in dynamic-host-catalog-aws
Screenshot 2024-06-19 at 3 25 37 PM

This error seems like is finding more than one DOM element within the selector. Perhaps we need to fine grain the selector to get the exact DOM element we want? happy to help if need.

**Comment by moduli** [comment]
@calcaide 

1. For the worker test to pass, we need to update the UI commit used in boundary. I tagged you in those PRS here. Please review when you have a chance.
- https://github.com/hashicorp/boundary/pull/4897
- https://github.com/hashicorp/boundary-enterprise/pull/1132

2. We had another locator conflict when an boundary resource id contained an `OK`. I'll update that locator in this branch to address that.

**Comment by calcaide** [comment]
> @calcaide
> 
> 1. For the worker test to pass, we need to update the UI commit used in boundary. I tagged you in those PRS here. Please review when you have a chance.
> 
> * [chore: Update UI version boundary#4897](https://github.com/hashicorp/boundary/pull/4897)
> * [chore: Update UI version boundary-enterprise#1132](https://github.com/hashicorp/boundary-enterprise/pull/1132)
> 
> 2. We had another locator conflict when an boundary resource id contained an `OK`. I'll update that locator in this branch to address that.

@moduli 

1. My apologize, last week I did not pay attention to GH notification center, so I did not see those PR's.
2. Gotcha, if you need any help or we want to use `test-selector` let me know 😉

**Comment by moduli** [comment]
Fix to the locator is already pushed to this branch. Should be good to review again.

**Review by calcaide — APPROVED** [review]
With latest changes I was able to run both `e2e:ent:docker` and `e2e:ent:aws` successful

**Pull request merged**
