### PR TITLE
Enable inline OIDC flow for admin

### PR DESCRIPTION
**Pull request by randallmorey**
This PR improves auth UX by enabling an "inline" OIDC flow, such that users will be shifted back into the admin UI after successfully authenticating.  Previously, users would land on a success message, requiring them to manually navigate back to the admin window.

To test this PR:
- Spin up Boundary dev and then run the UI externally, pointing it to the dev instance
- Click the OIDC "authenticate" button
- Log in and observe the provider window is automatically closed.
- Repeat to test OIDC "cancel" and "retry" features of the pending authentication dialog.

https://user-images.githubusercontent.com/8390120/117494076-d539c480-af41-11eb-94fe-558e1ef0ecc3.mov

### CODE REVIEW

**Review by calcaide — APPROVED** [review]
Tested the PR and repeat the tests with the "cancel" and "retry" features of the pending auth dialog. All works good :)

**Comment by gsusmi** [comment]
Works on Chrome(Version 90.0.4430.93 (Official Build) (x86_64)) and Safari(Version 14.1 (16611.1.21.161.6)) by closing inline-tabs and new windows after successful authentication. However, Firefox(88.0.1 (64-bit)) is complaining:
```
Error while processing route: scopes.scope.scopes.index window is null closeAll/<@http://localhost:4200/assets/admin.js:13233:84
closeAll@http://localhost:4200/assets/admin.js:13233:66
deactivate@http://localhost:4200/assets/admin.js:9761:26
exit@http://localhost:4200/assets/vendor.js:19863:12
setupContexts@http://localhost:4200/assets/vendor.js:62692:19
finalizeTransition@http://localhost:4200/assets/vendor.js:62612:14
getTransitionByIntent/newTransition.promise<@http://localhost:4200/assets/vendor.js:62551:21
invokeCallback@http://localhost:4200/assets/vendor.js:63760:17
publish@http://localhost:4200/assets/vendor.js:63743:23
@http://localhost:4200/assets/vendor.js:58133:61
invoke@http://localhost:4200/assets/vendor.js:56336:16
flush@http://localhost:4200/assets/vendor.js:56227:19
flush@http://localhost:4200/assets/vendor.js:56424:21
_end@http://localhost:4200/assets/vendor.js:56958:34
Backburner/this._boundAutorunEnd@http://localhost:4200/assets/vendor.js:56627:14
router.js:1243
Uncaught (in promise) TypeError: window is null
    closeAll window-manager.js:39
    closeAll window-manager.js:39
    deactivate oidc.js:70
    exit Ember
    setupContexts router_js.js:1699
    getTransitionByIntent router_js.js:1534
    transitionByIntent router_js.js:1469
    doTransition router_js.js:1605
    intermediateTransitionTo router_js.js:2081
    Ember 6
    trigger router_js.js:486
    finalizeTransition router_js.js:1641
    promise router_js.js:1558
    invokeCallback rsvp.js:493
    publish rsvp.js:476
    <anonymous> Ember
    invoke backburner.js:338
    flush backburner.js:229
    flush backburner.js:426
    _end backburner.js:960
    _boundAutorunEnd backburner.js:629
```
Let me know if you need additional info.

**Comment by randallmorey** [comment]
@gsusmi two things.  This error appears to be the result of Firefox blocking the popup by default.  Does it work when you allow the popup?  Secondly, the design seems wonky in Firefox.  The logo is too big.

**Comment by gsusmi** [comment]
Gotcha. It does indeed work on firefox with popups enabled. Ty!

**Pull request merged**
