### PR TITLE
[WIP] Switch to electron-builder

### PR DESCRIPTION
**Pull request by mdeggies**
To view the build/app bundle signing process, cd to `ui/desktop/electron-app` and run `yarn install && yarn dist`. For local running, you'll need an app developer ID cert in your keychain. 

```
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
✨  Done in 57.86s.
🌭~/go/boundary-update/boundary-ui/ui/desktop/electron-app: yarn dist
yarn run v1.22.5
$ electron-builder
  • electron-builder  version=22.9.1 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=10.1.5 appOutDir=dist/mac
  • default Electron icon is used  reason=application icon is not set
  • signing         file=dist/mac/boundary.app identityName=Developer ID Application: Hashicorp, Inc. ($ID) identityHash=$HASH provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/boundary-0.0.1-mac.zip
  • building        target=DMG arch=x64 file=dist/boundary-0.0.1.dmg
  • building block map  blockMapFile=dist/boundary-0.0.1.dmg.blockmap
  • building embedded block map  file=dist/boundary-0.0.1-mac.zip
✨  Done in 56.21s.: 
```

### CODE REVIEW

**Comment by gsusmi** [comment]
@mdeggies , I recently added (https://github.com/hashicorp/boundary-ui/pull/420) repo level yarn task `build:ui:desktop` to trigger DMG build for desktop client. It's using 'electron-forge/maker-dmg'. Just an fyi.
I'm also happy to help resolve package/yarn conflicts coz it could get a bit confusing with nested yarn workspaces.

**Comment by mdeggies** [comment]
Oh hey @gsusmi, that's great --  I didn't see that. I just wanted to push up my changes from before the break. Does electron forge codesign the app bundle? If so, we can totally use that. cc @shore

**Comment by gsusmi** [comment]
Got it. ElectronForge says so but I haven't tested it: https://www.electronjs.org/docs/tutorial/code-signing#electron-forge. Happy to go forward with electron-builder changes seeing as you already tested codesigning.

**Comment by mdeggies** [comment]
Closing, as y'all are moving forward with forge! :-)

**Pull request closed without merging**
