### PR TITLE
Icu 7028 fix quick setup container

### PR DESCRIPTION
**Pull request by DhariniJeeva**
[Jira](https://hashicorp.atlassian.net/browse/ICU-7028)

This pr fixes the layout of the quick setup container that was pushed to the corner. 

[quick setup](https://boundary-4p5k73owo-hashicorp.vercel.app/)

After fix:
Screen Shot 2022-11-22 at 12 25 48 PM
Screen Shot 2022-11-22 at 12 26 01 PM

Screen Shot 2022-11-22 at 12 25 41 PM

### CODE REVIEW

**Review by ZedLi — APPROVED** [review]
LGTM! Do you know what originally caused this?

**Review by cameronperera — APPROVED** [review]
LGTM.
Question about the screen shots. Is the "Creating your first target" screen a little too far right?

**Comment by DhariniJeeva** [comment]
> LGTM! Do you know what originally caused this?

Unfortunately, I couldn't. But moving the center layout to the parent container fixes the issue.

**Comment by DhariniJeeva** [comment]
> LGTM. Question about the screen shots. Is the "Creating your first target" screen a little too far right?

looks fine on the deployed links. The screenshot screen sizes aren't consistent here sorry!

**Comment by cameronperera** [comment]
> > LGTM! Do you know what originally caused this?
> 
> Unfortunately, I couldn't. But moving the center layout to the parent container fixes the issue.

Do you think it could have been the foot work we recently did? That was after the 0.11 release which would explain why we didn't see this during release testing.

**Comment by ZedLi** [comment]
> Do you think it could have been the foot work we recently did? That was after the 0.11 release which would explain why we didn't see this during release testing.

Yup it was, I just did a git bisect and that was the commit when it first appeared

**Review by dvonanderson — APPROVED** [review]

**Review by calcaide — APPROVED** [review]
Awesome job @DhariniJeeva

**Pull request closed without merging**
