### PR TITLE
chore: 🤖 Increase polling time desktop client

### PR DESCRIPTION
**Pull request by calcaide**
Increase polling time within desktop client.

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4128)

## Description

This PR increases polling time interval from `2.5` seconds to `18000` seconds (5h).

This change affects Targets and Sessions screens on the desktop client.

This change does not affect the Admin UI.

More context on those changes within the [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4128).

### CODE REVIEW

**Review by cameronperera — APPROVED** [review]
LGTM

**Review by ZedLi — APPROVED** [review]

**Review by DhariniJeeva — APPROVED** [review]
LGTM!

**Review by randallmorey — APPROVED** [review]

**Review by randallmorey — COMMENTED** [review]
What about admin?

**Comment by calcaide** [comment]
> What about admin?

https://github.com/hashicorp/boundary-ui/pull/1085

**Pull request merged**
