### PR TITLE
chore: 🤖 Migrate `form.input` to use `Form::Field::ListWrapper`

### PR DESCRIPTION
**Pull request by dvonanderson**
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12474

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12474)

## Description
- Migrate `form.input` used in `role/grants` to use `Form::Field::ListWrapper::TextInput` component
- Refactor `grants-test` to use `data-test-*` attributes, and clean up old logic

## Logic and View Changes
Note: There was some design and logic considerations that design has taken a look at, but also needs to be passed on to the team and reviewers of this PR.
- We will be using the `edit`  form action to control the logic for new grants as well as updating grants.  In our previous workflow, we didn't have this.  In our before version of `grants` if the user had ability to `set-grants` the input fields, delete and add grants functionality was never disabled .  The key here is that even if a user is setting brand new `grants` to a `role` they will still have to click the `edit` button to add those `grants`.

###  User with `setGrants` permissions: 
https://github.com/hashicorp/boundary-ui/assets/24277002/cf4c5279-e776-4be5-86af-bbb0e1e696b8

###  User with without `setGrants` permissions: 
https://github.com/hashicorp/boundary-ui/assets/24277002/89340451-8db1-4a18-a406-81d0579aa758

## How to Test for users that have `setGrants` permission
- Run this PR locally using `yarn test` or use the Vercel link provide below
- Click on "Roles" in the sidebar navigation
- Choose any role from screen and select the "Grants" tab
    - ensure that fields and buttons are disabled
- Click on "Edit Form" button
- Add an additional permission and click the "Add" button and click "Save"
    - ensure that the form saves
    - validate those permissions that you just created.
    - if you are using Boundary dev to test, we can also test the error messaging that will happen if the user inputs a wrong format permissions.
- Create  a `role` and `grants` that give a user or group  `read-only` access for `grants`

## How to Test for users that don't have `setGrants` permission
- From the previously created user that doesn't have `setGrants` permission click on "Roles" in the sidebar navigation
- Choose any role from the screen and select the "Grants' tab
    - ensure that the fields and buttons are disabled
    - ensure that the form actions that allow `edit` action is not visible
  

:technologist: [Admin preview](PATH_TO_FEATURE)

## Checklist:

- [x] I have added before and after screenshots for UI changes
~~- [ ] I have added JSON response output for API changes~~
- [x] I have added steps to reproduce and test for bug fixes in the description
~~- [ ] I have commented on my code, particularly in hard-to-understand areas~~
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by calcaide — CHANGES_REQUESTED** [review]
This PR contains errors/mistakes discussed on previous recent PR's. Please, review the feedback received in recent PR's within this PR

**Comment by dvonanderson** [comment]
> This PR contains errors/mistakes discussed on previous recent PR's. Please, review the feedback received in recent PR's within this PR

@calcaide  Every code snippets in this PR are patterns currently being used throughout the code base, please elaborate

**Comment by calcaide** [comment]
@dvonanderson 

I did not mention anything about code patterns. What I mean on my previous comment is this PR contained issues related to attribute arrangements and data-test- attributes.

This same feedback has been given consistently as "to fix" in past PR's that migrate the same as this one. Since the PR's shares the same purpose and context, I was asking you to review this PR with the feedback you received in previous PR's.

I see now, after my comment, you pushed changes to fix those.

I will appreciate if before asking others to review, you can give a review yourself, having in mind previous received feedback.

**Comment by calcaide** [comment]
Despite this PR adops HDS, it "breaks" the design. This implementation deleted the previous labels for ech field, so the user will have no labels per field, apart from confusing that goes agains i18n. (attached screenshots for better understanding)

I will close this PR and in the near future provide a new one adopting HDS but without breaking the design.

New implementation (missing labels):
Screenshot 2024-04-03 at 10 33 38 AM

Old implementation (with the right labels):
Screenshot 2024-04-03 at 10 35 04 AM

**Comment by dvonanderson** [comment]
you know i can see these right?

**Pull request closed without merging**
