### PR TITLE
fix: 🐛 upgrade cookie package

### PR DESCRIPTION
**Pull request by cameronperera**
# Description

This resolves this [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/166)
We had 2 versions of cookie, `0.6.0` & `0.4.1`.
By upgrading `socket.io` that upgraded `engine.io` which upgraded `cookie` to `0.7.2`.
Upgrading `express` to `cookie` to `0.7.1`.

Anything > `0.7.0` fixes our the security alert.

[Test release](https://github.com/hashicorp/boundary-ui-releases/actions/runs/11448516342)

## Checklist

- [ ] I have added before and after screenshots for UI changes
- [ ] I have added JSON response output for API changes
- [ ] I have added steps to reproduce and test for bug fixes in the description
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by lisbet-alvarez — APPROVED** [review]

**Review by ZedLi — APPROVED** [review]

**Review by calcaide — CHANGES_REQUESTED** [review]
After running `yarn why cookie` looks like we are bringing this old versions because third party dependencies of `ember-cli`.

Screenshot 2024-10-22 at 12 57 10 PM

My question is: Do we need to provide a fix urgently? otherwise, I will advocate for attempting to upgrade `ember-cli` and validate such upgrade brings versions of `cookie` without security vulnerabilities.

Let me know your thoughts.

**Comment by cameronperera** [comment]
> After running `yarn why cookie` looks like we are bringing this old versions because third party dependencies of `ember-cli`.
> 
> Screenshot 2024-10-22 at 12 57 10 PM
> My question is: Do we need to provide a fix urgently? otherwise, I will advocate for attempting to upgrade `ember-cli` and validate such upgrade brings versions of `cookie` without security vulnerabilities.
> 
> Let me know your thoughts.

That is a good point. Upgrading `ember-cli` might just resolve a good deal of our security alerts. I opted to go this route since we do have a hard push to resolve our security alerts but I can see how these are more bandaid fixes while an `ember-cli` upgrade is likely the real fix. Would you be ok with me doing that work in a separate branch? We could allow the smaller security alert related PRs to be merged, then focus on just upgrading `ember-cli`. I did see you have a ticket for it so I can use that.

**Comment by calcaide** [comment]
> > After running `yarn why cookie` looks like we are bringing this old versions because third party dependencies of `ember-cli`.
> > Screenshot 2024-10-22 at 12 57 10 PM
> > My question is: Do we need to provide a fix urgently? otherwise, I will advocate for attempting to upgrade `ember-cli` and validate such upgrade brings versions of `cookie` without security vulnerabilities.
> > Let me know your thoughts.
> 
> That is a good point. Upgrading `ember-cli` might just resolve a good deal of our security alerts. I opted to go this route since we do have a hard push to resolve our security alerts but I can see how these are more bandaid fixes while an `ember-cli` upgrade is likely the real fix. Would you be ok with me doing that work in a separate branch? We could allow the smaller security alert related PRs to be merged, then focus on just upgrading `ember-cli`. I did see you have a ticket for it so I can use that.

Hey @cameronperera 

Thank you for the work, totally agree with doing it in a separate PR.

Totally understandable about the push to fix. I am totally open to "force" versions or other kind of "fixes" for the sake of delivering within a due date, but if we know it's a fix and the real problem could be a dependenc upgrade, I will ask to create a ticket in jira to upgrade such dependency when we have time, and move on with the fix. All good on that front 😉

**Comment by cameronperera** [comment]
This was fixed with the `ember-cli` upgrade so I am closing this out.

**Pull request closed without merging**
