### PR TITLE
test(e2e): Updates from 0.18.0 testing

### PR DESCRIPTION
**Pull request by moduli**
This PR updates some Admin UI e2e tests based on testing it against Boundary 0.18.0. There were two changes here
- On the Auth Methods page, the `Manage` button and some of its options were not being found by the current selectors. Those selectors were updated.
- On the Alias test, for some reason, it was starting to fail more often due to what seems like a timing issue. The test's intention is to navigate from the Target details page to the associated Alias details page in order to clear its value. What seems like is happening...
  - Test is on Target details page
  - Test clicks on associated Alias to go to Alias details page
  - Test clicks Manage button
    - It seems like the test is clicking the Manage button on the Target details page (before the Alias page finishes loading)
  - The PR now adds a check to ensure that the Alias details page has loaded

## Testing
Tests against CE and ENT on both docker and aws infra were updated
```
# boundary
enos scenario launch e2e_ui_docker builder:local
yarn run e2e:ce:docker

enos scenario launch e2e_ui_aws builder:local
yarn run e2e:ce:aws

# boundary-enterprise
enos scenario launch e2e_ui_docker_ent builder:local
yarn run e2e:ent:docker

enos scenario launch e2e_ui_aws_ent builder:local
yarn run e2e:ent:aws
```

https://hashicorp.atlassian.net/browse/ICU-15234

### CODE REVIEW

**Comment by calcaide** [comment]
I am reproducing 1 issue (across all browsers) when running `yarn run e2e:ce:aws`.

Screenshot 2024-10-03 at 4 00 53 PM

Screenshot from the failure:
test-failed-1

As per the failure screenshot, seems like the "Manage" dropdow does not open.

Let me know if you want me to re-run 😉

**Comment by calcaide** [comment]
I am reproducing one issue running `yarn run e2e:ent:docker` under `boundary-ui-enterprise`. The issue reproduces within the 3 browsers

Screenshot 2024-10-03 at 4 30 32 PM

Screenshot 2024-10-03 at 4 30 50 PM

test-failed-1

**Comment by moduli** [comment]
@calcaide 
- The first issue was supposed to what I addressed. I'm not able to reproduce this on my machine yet. Still trying.
- The second issue was mentioned in the boundary-ui channel. There's a bug that someone is working on.

**Comment by calcaide** [comment]
> @calcaide
> 
> * The first issue was supposed to be what I addressed. I'm not able to reproduce this on my machine yet. Still trying.
> * The second issue was mentioned in the boundary-ui channel. There's a bug that someone is working on.

@moduli I am running the last set of tests `yarn run e2e:ent:aws`. Since the 2 other errors reported are under control, I will proceed to approve this PR as soon the test suite finishes 😉

**Comment by calcaide** [comment]
> @calcaide Pushed up a fix. Let me know if it resolves it on your end.

@moduli The fix works!! tests pass as expected 🥳

**Review by calcaide — APPROVED** [review]
Thanks for the terrific work 🙌

**Pull request merged**
