### PR TITLE
HDS-2827 Bump HDS to latest version

### PR DESCRIPTION
**Pull request by KristinLBradley**
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/HDS-2827)

## Description

If merged, this PR updates the Helios design system components (@hashicorp/design-system-components) to the latest version (^3.2.0)

## Checklist:

- [ ] ~~I have added before and after screenshots for UI changes~~
- [ ] ~~I have added JSON response output for API changes~~
- [ ] ~~I have added steps to reproduce and test for bug fixes in the description~~
- [ ] ~~I have commented on my code, particularly in hard-to-understand areas~~
- [x] My changes generate no new warnings
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

### CODE REVIEW

**Comment by KristinLBradley** [comment]
Seeing a few issues that I can't figure out: https://github.com/hashicorp/boundary-ui/pull/2017#issue-2017320609 @DhariniJeeva

**Comment by DhariniJeeva** [comment]
> Seeing a few issues that I can't figure out: [#2017 (comment)](https://github.com/hashicorp/boundary-ui/pull/2017#issue-2017320609) @DhariniJeeva

@KristinLBradley, I did not see any errors when I installed it. A new `yarn.lock` was generated when I tried the yarn install, and I added a commit to this PR with that change.  Not sure what was causing it, can you try clearing node modules and try again?

**Comment by KristinLBradley** [comment]
> > Seeing a few issues that I can't figure out: [#2017 (comment)](https://github.com/hashicorp/boundary-ui/pull/2017#issue-2017320609) @DhariniJeeva
> 
> @KristinLBradley, I did not see any errors when I installed it. A new `yarn.lock` was generated when I tried the yarn install, and I added a commit to this PR with that change. Not sure what was causing it, can you try clearing node modules and try again?

Thanks! Not sure why I was getting the issues before but it's fine now. :)

**Review by ZedLi — APPROVED** [review]
Thanks for the update!

**Comment by KristinLBradley** [comment]
Hoping it would be possible to merge this soon as it's a blocker to `Hds::CodeBlock` adoption. Thanks!

**Pull request merged**
