### PR TITLE
feat: 🎸 Add managed groups featuer flag for production

### PR DESCRIPTION
**Pull request by calcaide**

### CODE REVIEW

**Comment by DhariniJeeva** [comment]
could we remove the dev and test flags for `managed-groups`?

**Review by DhariniJeeva — COMMENTED** [review]
and I think we need to enable the flag on L100

**Review by randallmorey — CHANGES_REQUESTED** [review]
Let's flip the feature on line 100 so that it's on by default for all environments, and then remove environment-specific managed group flags.

**Review by DhariniJeeva — APPROVED** [review]
awesome! thank you!

**Review by gsusmi — APPROVED** [review]
LGTM. Ty!

**Pull request merged**
