### PR TITLE
chore: 🤖 upgrade ember-cli version

### PR DESCRIPTION
**Pull request by cameronperera**
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15393

# Description

chore: 🤖 upgrade ember-cli version
This upgrade should resolve a few different security alerts that we have. I will address those in a separate PR as I want to keep changes in packages low as we run tests, build, test locally, and test the release pipeline.

[Release test run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/11468678848)

## Checklist

- [ ] I have added before and after screenshots for UI changes
- [ ] I have added JSON response output for API changes
- [ ] I have added steps to reproduce and test for bug fixes in the description
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by ZedLi — APPROVED** [review]
Nice!

**Review by lisbet-alvarez — APPROVED** [review]
🥳

**Comment by calcaide** [comment]
@cameronperera 

We have some `resolutions` related to `ember-cli`, [here the code](https://github.com/hashicorp/boundary-ui/blob/main/package.json#L70-L74). Do we plan on audit/check if these are necessary after the `ember-cli` upgrade? I am fine if that happens in a separate PR, just checking 😉

**Review by calcaide — APPROVED** [review]
Left a couple of comments.

Great work!!

**Comment by cameronperera** [comment]
> @cameronperera After the `ember-cli` upgrade, seems to me we do not need anymore `lodash` patch.
> 
> * We can delete the `devDependencies` [here code](https://github.com/hashicorp/boundary-ui/blob/main/package.json#L51-L52).
> * We can delete the `post-install` script, [here code](https://github.com/hashicorp/boundary-ui/blob/main/package.json#L42).
> * We can delete the patch itself, [here code](https://github.com/hashicorp/boundary-ui/blob/main/patches/lodash.template%2B4.5.0.patch).
> 
> To validate such thing, I pull this branch, delete the mentioned above, perform a `rm -rf node_modules/ && yarn install` then run `yarn why lodash` and saw that we are resolving lodash `4.17.21` without using the patch.
> 
> Mentioning this because you have more context than me within the patch work, so if this validation process makes sense to you, we can get rid of it 😃 .
> 
> For the patch within `electron-app`, do not worry, because I will get rid of it [within this PR](https://github.com/hashicorp/boundary-ui/pull/2526/files) since after `electron-forge` upgrade seems not need anymore.
> 
> Let me know if I am missing something.

Thanks for the detailed response and yes, the plan was to remove the patch and resolutions once this is merged in. I will work on that right after I get this merged.

**Pull request merged**
